init:
  - cmd: npm install bower -g
  - cmd: npm install gulp -g

build_script:
  - cmd: git submodule update --init --recursive
  - ps: .\build.ps1 -Target "InstallCassandra" -Script "environment.cake"

test: off

cache:
- '%APPDATA%\npm-cache'
- 'src\Skimur.Web\node_modules'
- 'src\Skimur.Web\bower_components'
- '%HOMEDRIVE%%HOMEPATH%\.dnx\packages'
- 'tools\cassandra-2.2.4.msi'
