init:

build_script:
  - cmd: npm install bower -g
  - cmd: npm install gulp -g
  - cmd: git submodule update --init --recursive
  - ps: .\build.ps1 -Target "CI"

test: off

branches:
  only:
    - develop
    - main

cache:
- '%APPDATA%\npm-cache'
- 'src\Skimur.Web\node_modules'
- 'src\Skimur.Web\bower_components'
- '%HOMEDRIVE%%HOMEPATH%\.dnx\packages'
